convert:
  folder_count: 1
  output_path: ''
  source_path: D:/DMD/Forest
  test_ratio: 0.05
  train_ratio: 0.9
  use_depth: false
  use_stereo: true
  val_ratio: 0.05
inference:
  confidence_threshold: 1.0
  dataset_path: ''
  iou_threshold: 1.0
  max_det: 2000
  mode: 單張圖像推理
  model_path: D:/YOLO/runs/yolov12n_50epochs_20251022_1343/train/weights/best.pt
  output_path: ''
last_saved: '2025-12-25 16:07:41'
model_analyzer:
  file_type_filter: 所有類型
model_modifier:
  input_model: D:/YOLO/Model_file/PT_File/yolo11l.pt
  original_channels: 3
  output_model: D:\YOLO\Model_file\PT_File\yolo11l_modified.pt
  target_channels: 4
standard_training:
  advanced_params:
    auto_augment: randaugment
    beta1: 0.9
    beta2: 0.999
    bgr: 0.0
    cache: false
    close_mosaic: 10
    copy_paste: 0.0
    crop_fraction: 0.99
    data_loading_optimization: true
    degrees: 0
    device: auto
    early_stopping_min_delta: 0.001
    early_stopping_patience: 50
    erasing: 0.0
    fliplr: 0.5
    flipud: 0.0
    gpu_memory_optimization: true
    hsv_h: 0.15
    hsv_s: 0.7000000000000001
    hsv_v: 0.4
    lr_decay: 0.1
    lr_scheduler: auto
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    multi_gpu: false
    perspective: 0.0
    resume: false
    scale: 0.5
    shear: 0.0
    single_cls: false
    translate: 0.1
    val_frequency: 1
    val_iters: 32
    warmup_epochs: 3
    warmup_momentum: 0.8
    weight_decay: 0.0005
  amp: true
  batch_size: 32
  dataset_path: ''
  epochs: 10
  imgsz: 640
  learning_rate: 1
  model_file: ''
  optimizer: AdamW
  save_period: 10
  training_mode: pretrained
  workers: 0
stereo_inference:
  flip_non_pfm: false
  left_imgs: D:/DMD/Forest/Forest_Video_11/Img/Img0_13.png
  mixed_precision: true
  model_path: C:\Users\User\Downloads\YOLO-StereoVision_GUI_Trainer\runs\raft_stereo_20251224T2021\checkpoints\stereo_training\raft-stereo-20251224T2021.pth
  output_dir: C:/Users/User/Downloads/YOLO-StereoVision_GUI_Trainer/runs
  output_format: png
  right_imgs: D:/DMD/Forest/Forest_Video_11/Img/Img1_13.png
  save_numpy: false
  valid_iters: 16
stereo_training:
  advanced_params:
    context_norm: group
    corr_implementation: reg
    corr_levels: 4
    corr_radius: 4
    do_flip: 水平翻轉 Horizontal
    gamma_max: 1.2
    gamma_min: 0.8
    hidden_dims: 128x128x128 (默認)
    image_size: 640x480
    learning_rate: 0.0002
    mixed_precision: true
    n_downsample: 2
    n_gru_layers: 3
    noyjitter: false
    saturation_max: 1.4
    saturation_min: 0.0
    shared_backbone: false
    slow_fast_gru: false
    spatial_scale_max: 0.4
    spatial_scale_min: -0.2
    train_iters: 16
    valid_iters: 29
    weight_decay: 1.0e-05
  batch_size: 2
  dataset_path: Dataset\dataset_Stereo_20251215
  model_name: raftstereo-sceneflow.pth
  num_steps: 1000
  output_path: ''
window:
  geometry:
    height: 1240
    width: 1716
    x: 2
    y: 127
  last_tab_index: 6
